#!/usr/bin/env bash

set -e

if ! type "fauna" > /dev/null
then
    echo "Please install and configure fauna shell: https://github.com/fauna/fauna-shell"
    exit 1
fi

fql="$(go run . --sql "$2")"
echo "> $fql"

fauna eval --secret="$1" --format=shell "$fql"
